### ISSUE TITLE
Get a team name

### ISSUE THREAD

**Issue by akilankar** [refleep/nasa-appdev23#2]
- Priority change from "Bing Chilling (Low)" to "This is due soon (High) due to Mr Wilson's post on Google Classroom [Here](https://classroom.google.com/c/NjI2OTE1NTY5MTIz/p/NjM3NzIzNzE2MDI1/details) 

- Name is most likely Hang Nga 11 or whatever, final talkover due to member change needed

**Comment by infinitelmao** [comment]
Hằng Nga 11
